server {
    listen 80;

    types {
        application/dash+xml mpd;
        video/mp4 mp4 m4s;
        image/png png;
        image/jpeg jpg jpeg;
    }
    location / {
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Range';
            add_header 'Content-Length' 0;
            return 204;
        }
        root /usr/share/nginx/html;
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Range' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Range, Content-Length, Accept-Ranges' always;
    } 
}