services:

  db:
    image: mysql:8.0.21
    container_name: smi-db-service
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=smi_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    expose:
      - "3306"
      - "33060"
    volumes:
      - smi_mysql_data:/var/lib/mysql
    networks:
      - smi_network

  backend:
    build: ./
    image: smi-backend-service
    container_name: smi-backend-service
    environment:
      - PORT=3000
      - DATABASE_NAME=smi_db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - WAIT_HOSTS=db:3306
      - WAIT_TIMEOUT=120
      - OPENFIRE_HOST=smi-openfire
      - OPENFIRE_SECRET=secretkey
      - VIDEOS_DIR=/public/videos
      - USERS_DIR=/public/users
    ports:
      - "3000:3000"
    volumes:
      - ./volumes/public:/public
      - ./volumes/uploads:/uploads
    depends_on:
      - db
    networks:
      - smi_network

  web-server:
    image: nginx
    container_name: smi-web-server
    restart: always
    expose:
      - "80/tcp"
    ports:
      - "${STATIC_PORT:-8082}:80"
    volumes:
      - ./volumes/public/videos:/usr/share/nginx/html/videos:ro
      - ./volumes/public/users:/usr/share/nginx/html/users:ro
      - ./volumes/nginx-servidorweb.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NGINX_PORT=80
    networks:
      - smi_network

  frontend:
    image: nginx
    container_name: smi-frontend
    restart: always
    ports:
      - "${FRONTEND_PORT:-8081}:80"
    volumes:
      - ./volumes/public:/usr/share/nginx/html:ro
      - ./volumes/nginx-frontend.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NGINX_PORT=80
    networks:
      - smi_network
  
  openfire:
    image: miguelwill/docker-openfire
    container_name: smi-openfire
    restart: always
    ports:
      - "9090:9090"
      - "5222:5222"
      - "7070:7070"
    volumes:
      - ./volumes/lib-openfire/plugins:/var/lib/openfire/plugins
      - ./volumes/lib-openfire/logs:/var/lib/openfire/logs
    networks:
      - smi_network

networks:
  smi_network:
    driver: bridge

volumes:
  smi_mysql_data:
