version: '2'
services:
  backend_simple: # backend_simple service
    build: ./ # image is built from the configuration in ./Dockerfile (located in the current directory)
    image: books-backend_simple-service
    container_name: books-backend_simple-service
    environment: # container variables
      - PORT=3000
    ports: # container ports (right) redirected to host ports (left)
      - "3000:3000"